import { escapeXml as esc } from '../shared/model.mjs'
const head = `<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,noarchive,nosnippet"><meta name="referrer" content="same-origin"><title>私密地图</title>`
const loginStyle = `body{margin:0;background:#f4f4f5;color:#373a3c;font:16px/1.7 system-ui,"PingFang SC","Hiragino Sans",sans-serif}main{box-sizing:border-box;width:min(420px,calc(100% - 36px));margin:15vh auto;padding:30px;background:#fff;border:1px solid #e4e4e7;border-radius:16px}h1{font-size:24px;margin:0 0 12px}label,input,button{display:block;box-sizing:border-box;width:100%}input,button{font:inherit;padding:11px;margin:12px 0;border:1px solid #aaa;border-radius:8px}button{background:#25848a;color:white;border:0;cursor:pointer}:focus-visible{outline:3px solid #e18b38;outline-offset:3px}.error{color:#9b301b}`
export function loginPage(csrf, message = '') {
  return `<!doctype html><html lang="zh-CN"><head>${head}<style>${loginStyle}</style></head><body><main data-pagefind-ignore><h1>私密地图</h1><p>输入共享密码以继续。</p>${message ? `<p role="alert" class="error">${esc(message)}</p>` : ''}${csrf ? `<form action="/japan/auth" method="post"><input type="hidden" name="csrf" value="${esc(csrf)}"><label for="password">共享密码</label><input id="password" name="password" type="password" autocomplete="current-password" required maxlength="256"><button type="submit">进入地图</button></form>` : '<p>此页面暂未就绪，请稍后再试。</p>'}</main></body></html>`
}
export function mapPage(csrf) {
  return `<!doctype html><html lang="zh-CN"><head>${head}<meta name="japan-csrf" content="${esc(csrf)}"><link rel="stylesheet" href="/japan/assets/app.css"><script type="module" src="/japan/assets/app.js"></script></head><body class="japan"><main id="japan-app" data-pagefind-ignore>
<header class="j-top"><div><strong id="trip-title">私密地图</strong><small id="updated">正在读取…</small></div><div class="j-actions"><button id="toggle-panel" aria-controls="panel" aria-expanded="true">日程与筛选</button><form action="/japan/logout" method="post" id="logout"><input type="hidden" name="csrf" value="${esc(csrf)}"><button type="submit">退出登录</button></form></div></header>
<div class="j-workspace"><section class="j-map-area" aria-label="交互地图"><div id="map" tabindex="0" aria-label="地图，可用方向键平移，加减键缩放"></div><div class="j-map-caption"><strong id="map-title">正在读取地图</strong><span id="count"></span><small>连线为走廊示意；箭头按原节点顺序，回程方向见备注。</small></div><div class="j-base-status" role="status"><span id="base-status">详细底图正在连接…</span><button id="retry-tiles" hidden>重试底图</button><button id="fallback" hidden>仅查看点线与日程</button></div></section>
<aside id="panel" class="j-panel" aria-label="日程与地点"><div id="fatal" role="alert"></div><div class="j-controls">
<label for="day">日期（日本时间）</label><div class="j-day-nav"><button id="previous" aria-label="上一日">←</button><select id="day"><option value="0">全程概览</option></select><button id="next" aria-label="下一日">→</button></div>
<div id="regions" class="j-chips" aria-label="地区快速定位"></div><label for="search">搜索中文、日文或车站名</label><input type="search" id="search" placeholder="搜索地点与到达方式" autocomplete="off">
<label for="lake">湖区方案（整段替换）</label><select id="lake"></select>
<details><summary>图层与图例</summary><label><input id="optional" type="checkbox" checked>显示可选与协作候选地点</label><label><input id="labels" type="checkbox" checked>显示地点标签</label><div id="categories" class="j-checks"></div><div id="modes" class="j-checks"></div><p class="j-muted">摄影视线：仅摄影方向，非步行路线。</p></details>
</div><section id="detail" aria-live="polite"></section><section id="summary"></section><section id="list"></section>
<details id="collaboration"><summary>共同补充目的地</summary><p>新增地点作为待核实候选；昵称用于标注贡献者。原始行程保留。</p><button id="refresh">刷新协作更新</button><form id="add-point"><input name="id" type="hidden"><label>你的昵称<input name="author" required maxlength="60" autocomplete="nickname"></label><label>中文名称<input name="name" required maxlength="120"></label><label>日文名称<input name="jp" maxlength="120"></label><div class="j-columns"><label>纬度<input name="lat" type="number" step="any" min="20" max="50" required></label><label>经度<input name="lon" type="number" step="any" min="120" max="155" required></label></div><button id="pick" type="button">在地图上点选位置</button><label>日期<select name="day" required></select></label><label>地区<select name="region"></select></label><label>类别<select name="category"></select></label><label>所属方案<select name="variant"></select></label><label>建议时间<input name="time" maxlength="300"></label><label>停留长度<input name="stay" maxlength="200"></label><label>到达方式<textarea name="access" maxlength="1500"></textarea></label><label>备注<textarea name="note" maxlength="3000"></textarea></label><label>资料来源网址<input name="source_url" type="url" maxlength="1000"></label><button type="submit">保存候选地点</button><button id="cancel-edit" type="button" hidden>取消编辑</button><p id="save-status" role="status"></p></form></details>
<details id="sources"><summary>来源、许可与导出</summary><div id="source-list"></div><p><a href="https://leafletjs.com/" target="_blank" rel="noopener noreferrer">Leaflet（BSD-2-Clause）</a> · <a href="https://www.gsi.go.jp/kikakuchousei/kikakuchousei40182.html" target="_blank" rel="noopener noreferrer">国土地理院利用条款</a></p><p>底图仅按当前视窗在线加载；不提供离线缓存。</p><a href="/japan/export/geojson">导出全部方案 GeoJSON</a> · <a href="/japan/export/kml">导出全部方案 KML</a></details>
</aside></div></main><noscript><p>交互地图需要 JavaScript。退出登录仍可使用页面顶部表单。</p></noscript></body></html>`
}
